#!/usr/bin/env bash
# generated by cx-tooling-author; edits will be overwritten on next render
#
# install-lsp.sh — build the CX language server and place it under
# ~/.local/share/cx-lsp/. Sourced/dispatched by install.sh.

set -euo pipefail

: "${REPO:?install-lsp.sh: REPO env not set — invoke via install.sh}"
LSP_SRC="$REPO/tooling/lsp"
LSP_DST="$HOME/.local/share/cx-lsp"

if [ ! -d "$LSP_SRC" ]; then
  echo "install-lsp.sh: $LSP_SRC not found" >&2
  exit 1
fi

SRC_VERSION="$(node -p "require('$LSP_SRC/package.json').version" 2>/dev/null || echo unknown)"
DST_VERSION=""
if [ -f "$LSP_DST/package.json" ]; then
  DST_VERSION="$(node -p "require('$LSP_DST/package.json').version" 2>/dev/null || echo unknown)"
fi

if [ "$DST_VERSION" = "$SRC_VERSION" ] && [ -f "$LSP_DST/out/server.js" ]; then
  echo "LSP: $DST_VERSION already installed at $LSP_DST — skipping"
  exit 0
fi

if [ ! -f "$LSP_SRC/out/server.js" ]; then
  echo "LSP: building (make build-lsp)..."
  ( cd "$REPO" && make build-lsp )
fi

if [ ! -d "$LSP_SRC/node_modules" ]; then
  echo "LSP: installing node_modules..."
  ( cd "$LSP_SRC" && npm install --omit=dev --silent )
fi

if [ -d "$LSP_DST" ]; then
  echo "LSP: removing stale $LSP_DST (was $DST_VERSION)"
  rm -rf "$LSP_DST"
fi

mkdir -p "$LSP_DST"
cp -R "$LSP_SRC/out" "$LSP_DST/out"
cp -R "$LSP_SRC/node_modules" "$LSP_DST/node_modules"
cp "$LSP_SRC/package.json" "$LSP_DST/package.json"

if [ ! -f "$LSP_DST/out/server.js" ]; then
  echo "install-lsp.sh: build output missing at $LSP_DST/out/server.js" >&2
  exit 1
fi

echo "LSP: installed $SRC_VERSION at $LSP_DST"
