#!/usr/bin/env bash
# generated by cx-tooling-author; edits will be overwritten on next render
#
# CX editor tooling installer.
# Installs the CX language server, tree-sitter parser, Neovim Lua module,
# and/or the VS Code extension for the current user.
#
# Usage:
#   ./install.sh                  # install both editors (default)
#   ./install.sh --nvim           # Neovim only
#   ./install.sh --vscode         # VS Code only
#   ./install.sh --uninstall      # remove everything this script installs
#   ./install.sh --force          # overwrite a hand-edited ~/.config/nvim/lua/plugins/cx.lua without backup
#   ./install.sh --repo PATH      # cx-private checkout (default: auto-detected)
#   ./install.sh --help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

REPO=""
DO_NVIM=0
DO_VSCODE=0
DO_UNINSTALL=0
FORCE=0
EXPLICIT_EDITOR=0

usage() {
  sed -n '3,15p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --nvim) DO_NVIM=1; EXPLICIT_EDITOR=1; shift ;;
    --vscode) DO_VSCODE=1; EXPLICIT_EDITOR=1; shift ;;
    --uninstall) DO_UNINSTALL=1; shift ;;
    --force) FORCE=1; shift ;;
    --repo) REPO="$2"; shift 2 ;;
    --repo=*) REPO="${1#--repo=}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "install.sh: unknown arg: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [ "$EXPLICIT_EDITOR" -eq 0 ]; then
  DO_NVIM=1
  DO_VSCODE=1
fi

if [ -z "$REPO" ]; then
  REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
fi

if [ ! -d "$REPO/tooling" ]; then
  echo "install.sh: $REPO/tooling not found — pass --repo /path/to/cx-private" >&2
  exit 1
fi

export REPO
export FORCE
export DO_NVIM
export DO_VSCODE
export DO_UNINSTALL

WARNINGS=()
export_warnings_path="$(mktemp -t cx-install-warnings.XXXXXX)"
trap 'rm -f "$export_warnings_path"' EXIT
export CX_INSTALL_WARNINGS="$export_warnings_path"

# shellcheck source=preflight.sh
. "$SCRIPT_DIR/preflight.sh"

if [ "$DO_UNINSTALL" -eq 1 ]; then
  bash "$SCRIPT_DIR/uninstall.sh"
  exit $?
fi

if ! preflight_run; then
  echo "install.sh: preflight checks failed — fix the blockers above and re-run" >&2
  exit 1
fi

RESULT_NVIM="skipped"
RESULT_VSCODE="skipped"
NVIM_EXIT=0
VSCODE_EXIT=0

if [ "$DO_NVIM" -eq 1 ]; then
  echo
  echo "=== installing Neovim support ==="
  if bash "$SCRIPT_DIR/install-lsp.sh" && bash "$SCRIPT_DIR/install-nvim.sh"; then
    RESULT_NVIM="installed"
  else
    RESULT_NVIM="FAILED"
    NVIM_EXIT=$?
  fi
fi

if [ "$DO_VSCODE" -eq 1 ]; then
  echo
  echo "=== installing VS Code support ==="
  if bash "$SCRIPT_DIR/install-lsp.sh" && bash "$SCRIPT_DIR/install-vscode.sh"; then
    RESULT_VSCODE="installed"
  else
    RESULT_VSCODE="FAILED"
    VSCODE_EXIT=$?
  fi
fi

echo
echo "=== summary ==="
printf '  Neovim   %s\n' "$RESULT_NVIM"
printf '  VS Code  %s\n' "$RESULT_VSCODE"

if [ -s "$CX_INSTALL_WARNINGS" ]; then
  echo
  echo "warnings:"
  sed 's/^/  - /' "$CX_INSTALL_WARNINGS"
fi

if [ "$RESULT_NVIM" = "FAILED" ] && [ "$RESULT_VSCODE" = "FAILED" ]; then
  exit 1
fi
if [ "$RESULT_NVIM" = "FAILED" ] || [ "$RESULT_VSCODE" = "FAILED" ]; then
  exit 2
fi
exit 0
