#!/usr/bin/env bash
# generated by cx-tooling-author; edits will be overwritten on next render
#
# install-vscode.sh — package (if needed) and install the CX VS Code
# extension. Dispatched by install.sh.

set -euo pipefail

: "${REPO:?install-vscode.sh: REPO env not set — invoke via install.sh}"

VSCODE_SRC="$REPO/tooling/vscode"
EXTENSION_ID="cx-language"

if [ ! -d "$VSCODE_SRC" ]; then
  echo "install-vscode.sh: $VSCODE_SRC not found" >&2
  exit 1
fi

# Pick the highest-semver .vsix in tooling/vscode/. Fall back to building one
# if none exists.
pick_latest_vsix() {
  ls "$VSCODE_SRC"/cx-language-*.vsix 2>/dev/null \
    | awk -F'cx-language-|\\.vsix' '{print $2 "\t" $0}' \
    | sort -V \
    | tail -n1 \
    | cut -f2
}

VSIX="$(pick_latest_vsix)"
if [ -z "$VSIX" ]; then
  echo "vscode: no .vsix found — building (make build-vscode)..."
  ( cd "$REPO" && make build-vscode )
  VSIX="$(pick_latest_vsix)"
fi

if [ -z "$VSIX" ] || [ ! -f "$VSIX" ]; then
  echo "install-vscode.sh: no .vsix available after build attempt" >&2
  exit 1
fi

SRC_VERSION="$(basename "$VSIX" | sed -E 's/^cx-language-(.*)\.vsix$/\1/')"
echo "vscode: target version $SRC_VERSION at $VSIX"

# Detect existing installs (any publisher) of cx-language. The VS Code
# Marketplace publisher prefix may vary if this was sideloaded under a
# different scope; uninstall anything matching cx-language to avoid duplicates.
EXISTING="$(code --list-extensions --show-versions 2>/dev/null | grep -E "(^|\.)${EXTENSION_ID}@" || true)"
if [ -n "$EXISTING" ]; then
  while IFS= read -r line; do
    ext_id="${line%@*}"
    ext_ver="${line#*@}"
    if [ "$ext_ver" = "$SRC_VERSION" ]; then
      echo "vscode: $ext_id@$ext_ver already installed — re-installing with --force to refresh"
    else
      echo "vscode: replacing $ext_id@$ext_ver with $SRC_VERSION"
    fi
    code --uninstall-extension "$ext_id" >/dev/null 2>&1 || true
  done <<< "$EXISTING"
fi

code --install-extension "$VSIX" --force
echo "vscode: installed $SRC_VERSION — reload VS Code, then open a .cx file"
