#!/usr/bin/env bash
# generated by cx-tooling-author; edits will be overwritten on next render
# (template updated 2026-08-20 to the plugin-root layout — tooling/neovim is a
#  native vim.lsp.config plugin root: lua/cx/init.lua + plugin/cx.lua +
#  ftplugin/ + indent/ + syntax/. No nvim-lspconfig. The single-file cx.lua
#  copy flow is retired.)
#
# Installs CX support for Neovim >= 0.11:
#   1. the tree-sitter grammar via tooling/tree-sitter-cx `make install-nvim`
#      (ad-hoc signs the parser, installs to a FRESH inode, and ends with a
#      headless load-proof — the #883 editor-kill pattern-breaker)
#   2. the editor plugin:
#      - lazy.nvim/LazyVim: writes ~/.config/nvim/lua/plugins/cx.lua with a
#        `dir =` spec pointing at this checkout (backup-on-differ), or
#      - plain Neovim: copies the plugin root into
#        ~/.local/share/nvim/site/pack/cx/start/cx-nvim
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PLUGIN_ROOT="$REPO/tooling/neovim"
CX_BIN_DEFAULT="$REPO/vcx/target/cx"
FORCE="${1:-}"

command -v nvim >/dev/null 2>&1 || { echo "nvim: not on PATH — install Neovim >= 0.11 first"; exit 1; }
NVIM_MINOR="$(nvim --version | head -1 | sed -E 's/^NVIM v[0-9]+\.([0-9]+).*/\1/')"
[ "$NVIM_MINOR" -ge 11 ] || { echo "nvim: Neovim >= 0.11 required (native vim.lsp.config)"; exit 1; }

# 1. tree-sitter grammar (signed, fresh-inode, load-proofed — see #883)
make -C "$REPO/tooling/tree-sitter-cx" install-nvim

# 2. the plugin
LAZY_SPEC_DIR="$HOME/.config/nvim/lua/plugins"
if [ -d "$HOME/.config/nvim/lua/plugins" ] || [ -f "$HOME/.config/nvim/lazy-lock.json" ]; then
  mkdir -p "$LAZY_SPEC_DIR"
  SPEC="$LAZY_SPEC_DIR/cx.lua"
  TMP="$(mktemp)"
  cat > "$TMP" <<SPEC_EOF
-- generated by cx-tooling-author (tooling/install/install-nvim.sh)
return {
  {
    dir = '$PLUGIN_ROOT',
    init = function()
      vim.env.CX_BIN = vim.env.CX_BIN or '$CX_BIN_DEFAULT'
    end,
  },
}
SPEC_EOF
  if [ -f "$SPEC" ] && ! cmp -s "$SPEC" "$TMP"; then
    if [ "$FORCE" != "--force" ]; then
      bak="$SPEC.bak.$(date +%Y%m%d-%H%M%S)"
      cp "$SPEC" "$bak"
      echo "nvim: existing plugins/cx.lua differs — backed up to $bak"
    fi
  fi
  mv "$TMP" "$SPEC"
  echo "nvim: lazy.nvim spec installed at $SPEC (dir = $PLUGIN_ROOT)"
else
  PACK_DST="$HOME/.local/share/nvim/site/pack/cx/start/cx-nvim"
  rm -rf "$PACK_DST"
  mkdir -p "$PACK_DST"
  cp -R "$PLUGIN_ROOT"/. "$PACK_DST"/
  echo "nvim: plugin copied to $PACK_DST (set CX_BIN or put cx on PATH)"
fi

# 3. smoke: the plugin must load headless
nvim --headless "+lua require('cx').setup()" "+qa!" 2>/dev/null \
  && echo "nvim: headless setup smoke OK" \
  || { echo "nvim: headless setup smoke FAILED"; exit 1; }
echo "nvim: done. Restart Neovim."
