#!/usr/bin/env bash
# generated by cx-tooling-author; edits will be overwritten on next render
#
# preflight.sh — sourced by install.sh.
# Defines preflight_run; returns 0 if no hard blockers, 1 otherwise.
# Soft warnings are appended to $CX_INSTALL_WARNINGS (one per line).

# Required env from install.sh: REPO, DO_NVIM, DO_VSCODE, CX_INSTALL_WARNINGS

_pf_warn() {
  printf '%s\n' "$1" >> "$CX_INSTALL_WARNINGS"
}

_pf_os() {
  case "$(uname -s)" in
    Darwin) echo darwin ;;
    Linux)  echo linux ;;
    *)      echo unknown ;;
  esac
}

_pf_check_node() {
  if ! command -v node >/dev/null 2>&1; then
    echo "  [block] node not found — install Node 20+ (brew install node / apt install nodejs)"
    return 1
  fi
  local v
  v="$(node --version 2>/dev/null | sed 's/^v//' | cut -d. -f1)"
  if [ -z "$v" ] || [ "$v" -lt 20 ]; then
    echo "  [block] node $(node --version) is too old — need Node 20+"
    return 1
  fi
  echo "  [ok] node $(node --version)"
  return 0
}

_pf_check_make() {
  if ! command -v make >/dev/null 2>&1; then
    echo "  [block] make not found — install build tools (brew install make / apt install build-essential)"
    return 1
  fi
  echo "  [ok] make"
  return 0
}

_pf_check_tree_sitter() {
  if ! command -v tree-sitter >/dev/null 2>&1; then
    echo "  [block] tree-sitter CLI not found — install via 'npm i -g tree-sitter-cli' or 'cargo install tree-sitter-cli'"
    return 1
  fi
  echo "  [ok] tree-sitter $(tree-sitter --version 2>/dev/null | head -n1)"
  return 0
}

_pf_check_nvim() {
  if ! command -v nvim >/dev/null 2>&1; then
    echo "  [block] nvim not found — install Neovim 0.9+ or re-run with --vscode only"
    return 1
  fi
  local raw major minor
  raw="$(nvim --version 2>/dev/null | head -n1 | sed -E 's/^NVIM v?([0-9]+\.[0-9]+).*/\1/')"
  major="${raw%%.*}"
  minor="${raw##*.}"
  if [ -z "$major" ] || { [ "$major" -eq 0 ] && [ "$minor" -lt 9 ]; }; then
    echo "  [block] nvim $raw too old — need 0.9+ for tree-sitter parser API"
    return 1
  fi
  echo "  [ok] nvim $raw"
  if ! find "$HOME/.local/share/nvim/site/pack" -maxdepth 6 -type d -name 'nvim-treesitter' 2>/dev/null | grep -q .; then
    if ! find "$HOME/.config/nvim" -maxdepth 6 -type f \( -name '*.lua' -o -name '*.vim' \) 2>/dev/null \
       | xargs grep -l 'nvim-treesitter' 2>/dev/null | grep -q .; then
      _pf_warn "nvim-treesitter plugin not detected — the CX parser will install but won't render highlights without it"
    fi
  fi
  return 0
}

_pf_check_code() {
  if command -v code >/dev/null 2>&1; then
    echo "  [ok] code CLI on PATH"
    return 0
  fi
  case "$(_pf_os)" in
    darwin)
      if [ -d "/Applications/Visual Studio Code.app" ]; then
        _pf_warn "VS Code is installed but 'code' is not on PATH — in VS Code: Cmd+Shift+P → 'Shell Command: Install code command in PATH'"
        echo "  [block] code CLI not on PATH (see warnings)"
        return 1
      fi
      ;;
    linux)
      for p in /snap/bin/code /var/lib/flatpak/exports/bin/com.visualstudio.code; do
        if [ -x "$p" ]; then
          _pf_warn "VS Code detected at $p but 'code' is not on PATH — flatpak/snap installs may not support --install-extension; consider manual .vsix install"
          echo "  [block] code CLI not on PATH (see warnings)"
          return 1
        fi
      done
      ;;
  esac
  echo "  [block] code CLI not found — install VS Code, or re-run with --nvim only"
  return 1
}

_pf_check_xdg_writable() {
  local fail=0
  for d in "$HOME/.local/share" "$HOME/.config"; do
    if ! mkdir -p "$d" 2>/dev/null || [ ! -w "$d" ]; then
      echo "  [block] $d is not writable"
      fail=1
    fi
  done
  if [ "$fail" -eq 0 ]; then
    echo "  [ok] ~/.local/share and ~/.config writable"
  fi
  return $fail
}

preflight_run() {
  local rc=0
  echo "preflight:"
  echo "  [info] os=$(_pf_os) repo=$REPO"
  _pf_check_node       || rc=1
  _pf_check_make       || rc=1
  _pf_check_xdg_writable || rc=1
  if [ "$DO_NVIM" -eq 1 ]; then
    _pf_check_tree_sitter || rc=1
    _pf_check_nvim        || rc=1
  fi
  if [ "$DO_VSCODE" -eq 1 ]; then
    _pf_check_code || rc=1
  fi
  return $rc
}
