#!/usr/bin/env bash
# generated by cx-tooling-author; edits will be overwritten on next render
#
# uninstall.sh — reverse what install-{lsp,nvim,vscode}.sh placed on the
# system. A hand-edited lazy.nvim spec is preserved as a .bak.<ts> copy before removal.

set -euo pipefail

LSP_DST="$HOME/.local/share/cx-lsp"
PARSER_DST="$HOME/.local/share/nvim/site/parser/cx.so"
QUERY_DST_DIR="$HOME/.local/share/nvim/site/queries/cx"
LUA_DST="$HOME/.config/nvim/lua/plugins/cx.lua"
PACK_DST="$HOME/.local/share/nvim/site/pack/cx/start/cx-nvim"
EXTENSION_ID="cx-language"

echo "uninstall: removing CX editor tooling"

if [ -d "$LSP_DST" ]; then
  rm -rf "$LSP_DST"
  echo "  removed $LSP_DST"
else
  echo "  skip  $LSP_DST (absent)"
fi

if [ -f "$PARSER_DST" ]; then
  rm -f "$PARSER_DST"
  echo "  removed $PARSER_DST"
else
  echo "  skip  $PARSER_DST (absent)"
fi

if [ -d "$QUERY_DST_DIR" ]; then
  rm -rf "$QUERY_DST_DIR"
  echo "  removed $QUERY_DST_DIR"
else
  echo "  skip  $QUERY_DST_DIR (absent)"
fi

if [ -f "$LUA_DST" ]; then
  bak="$LUA_DST.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$LUA_DST" "$bak"
  rm -f "$LUA_DST"
  echo "  removed $LUA_DST (backup: $bak)"
else
  echo "  skip  $LUA_DST (absent)"
fi

if command -v code >/dev/null 2>&1; then
  EXISTING="$(code --list-extensions 2>/dev/null | grep -E "(^|\.)${EXTENSION_ID}$" || true)"
  if [ -n "$EXISTING" ]; then
    while IFS= read -r ext_id; do
      code --uninstall-extension "$ext_id" >/dev/null 2>&1 || true
      echo "  removed VS Code extension $ext_id"
    done <<< "$EXISTING"
  else
    echo "  skip  VS Code extension (none matching $EXTENSION_ID)"
  fi
else
  echo "  skip  VS Code extension (code CLI not on PATH)"
fi

cat <<'EOF'

uninstall: done.

Note: you may want to remove the `require('cx')` line from your
~/.config/nvim/init.lua manually — this script does not edit init.lua.
EOF

rm -rf "$PACK_DST"
