module cxstore

import os

// RULED: CO-1 (#974, ledger/rulings_2026_08_25_0170_closeout.md) — store
// multicodec read-compat.
//
// v0.16 (8fafb76fa) gave the formerly-RESERVED entry u16 at offset 6 a meaning
// and made the reader fail closed on every code but sha2-256. v0.15's writer
// had been emitting a literal `0` into that slot, so the change retroactively
// made every v0.15 store unopenable — a stored-format break shipped as a
// no-format-change release.
//
// CO-1: readers accept EXACTLY {0x0000, 0x0012}. Zero is not a second live
// encoding — v0.15 had one hash algorithm, so zero MEANS sha2-256 for every
// pack that can legally exist. Everything else keeps failing closed. The first
// durable write to a store holding zero slots stamps them forward in place.
//
// The fixture (vcx/tests/testdata/v015_pack_compat/) is committed and FROZEN:
// a pack written by the current engine with exactly one difference applied —
// every entry's multicodec slot zeroed — so a green pin here isolates the one
// variable and nothing else. It is regenerated by
// `third_party/v/v run vcx/tools/regen_v015_pack_fixture/`, which walks the
// entry chain independently of the footer index and refuses to author a
// fixture from a pack whose slots do not already read 0x0012.

// The payloads the fixture generator wrote — duplicated deliberately: the pin
// is that these EXACT bytes come back out of a v0.15-shaped pack, which is a
// claim about the committed file, not about a shared helper.
const compat_fixture_payloads = [
	'cx-v015-compat: alpha',
	'cx-v015-compat: beta',
	'cx-v015-compat: gamma',
	'cx-v015-compat: delta',
	'cx-v015-compat: epsilon',
]

const compat_fixture_pack = 'store-0000.cxpack'

// compat_entry_codes walks the ENTRY CHAIN — offset 64, then by entry_length —
// and returns each entry's multicodec slot. Deliberately not the footer-index
// walk the reader uses: these pins are about bytes on disk, so they read them
// the way the fixture generator wrote them, independently of the index.
fn compat_entry_codes(data []u8) []u16 {
	flen := read_u64(data, data.len - 8)
	chain_end := data.len - 8 - int(flen)
	mut codes := []u16{}
	mut off := header_size
	for off < chain_end {
		elen := int(read_u32(data, off))
		if elen < 44 || off + elen > chain_end {
			break // malformed — the caller's count assertion reports it
		}
		codes << read_u16(data, off + 6)
		off += elen
	}
	return codes
}

fn compat_fixture_dir() string {
	// vcx/cxstore/<this file> → vcx → vcx/tests/testdata/v015_pack_compat
	return os.join_path(os.dir(os.dir(@FILE)), 'tests', 'testdata', 'v015_pack_compat')
}

// compat_store_copy stages a WRITABLE copy of the frozen fixture store, so a
// pin that exercises the in-place stamp never mutates the committed bytes.
fn compat_store_copy(name string) !string {
	dir := os.join_path(os.temp_dir(), name)
	os.rmdir_all(dir) or {}
	os.mkdir_all(dir)!
	os.cp(os.join_path(compat_fixture_dir(), compat_fixture_pack), os.join_path(dir,
		compat_fixture_pack))!
	return dir
}

// ── pin (a): the v0.15-shaped pack OPENS and READS ────────────────────────

fn test_v015_zero_slot_pack_opens_and_reads() {
	path := os.join_path(compat_fixture_dir(), compat_fixture_pack)
	assert os.exists(path), 'fixture missing: ${path} (regenerate with vcx/tools/regen_v015_pack_fixture)'
	data := os.read_bytes(path) or {
		assert false, 'read fixture: ${err}'
		return
	}
	// The committed bytes really are the v0.15 shape — every entry slot zero.
	codes := compat_entry_codes(data)
	assert codes.len == compat_fixture_payloads.len
	for c in codes {
		assert c == pack_hash_mh_code_legacy_zero, 'fixture is not zero-slotted: 0x${c:04x}'
	}
	r := open_pack(path) or {
		assert false, 'open_pack refused a v0.15 zero-slot pack: ${err}'
		return
	}
	// The reader NAMES what it accepted, so the write path can migrate it.
	assert r.legacy_hash_slots == compat_fixture_payloads.len
	// And every object round-trips — get() self-verifies against doc_hash, so a
	// payload coming back at all proves zeroing the slot broke no hash.
	for p in compat_fixture_payloads {
		bytes := p.bytes()
		got := r.get(object_name(bytes)) or {
			assert false, 'v0.15 pack lost ${p}'
			return
		}
		assert got == bytes
	}
	r.close()
}

// ── pins (b) + (c): a republish succeeds AND stamps the slots forward ─────

fn test_republish_onto_a_v015_store_stamps_the_slots() {
	dir := compat_store_copy('cxstore_v015_republish') or {
		assert false, 'stage fixture: ${err}'
		return
	}
	fixture := os.join_path(dir, compat_fixture_pack)
	mut b := open_pack_object_backend(dir)
	b.seed_index() or {
		assert false, 'seed_index refused a v0.15 store: ${err}'
		return
	}
	assert b.object_count() == compat_fixture_payloads.len
	// The open recorded the migration debt without doing any extra I/O.
	assert b.legacy_slot_packs == [fixture]

	// (b) the republish itself.
	fresh := 'cx-v017-republished'.bytes()
	b.put_object(fresh) or {
		assert false, 'put_object: ${err}'
		return
	}
	b.flush_segment() or {
		assert false, 'republish onto a v0.15 store failed: ${err}'
		return
	}
	assert b.legacy_slot_packs.len == 0, 'migration debt survived the write'
	assert os.exists(os.join_path(dir, 'store-0001.cxpack')), 'the new segment did not land'

	// (c) the v0.15 pack is now current-format, in place.
	after := os.read_bytes(fixture) or {
		assert false, 'read stamped fixture: ${err}'
		return
	}
	stamped := compat_entry_codes(after)
	assert stamped.len == compat_fixture_payloads.len
	for c in stamped {
		assert c == pack_hash_mh_code, 'slot not stamped: 0x${c:04x}'
	}
	// The stamp is a 2-byte edit and NOTHING else: same file length, and the
	// only differing bytes are the multicodec slots.
	before := os.read_bytes(os.join_path(compat_fixture_dir(), compat_fixture_pack)) or {
		assert false, 'read pristine fixture: ${err}'
		return
	}
	assert after.len == before.len, 'the stamp resized the pack'
	mut diffs := 0
	for i in 0 .. before.len {
		if before[i] != after[i] {
			diffs++
		}
	}
	// One byte per entry: the slot's high byte is 0 in both shapes.
	assert diffs == compat_fixture_payloads.len, 'the stamp touched ${diffs} bytes, expected ${compat_fixture_payloads.len}'

	// Everything still reads — old objects and new — through a FRESH open, so
	// no in-memory state is covering for the rewritten file. This is the live
	// proof that the slot is covered by no hash, CRC, or signature: a pack
	// whose checksums depended on it would now fail its own integrity checks.
	mut b2 := open_pack_object_backend(dir)
	loaded := b2.load_objects() or {
		assert false, 'reload after stamp: ${err}'
		return
	}
	assert loaded.len == compat_fixture_payloads.len + 1
	assert b2.legacy_slot_packs.len == 0, 'a stamped store still reports migration debt'
	for p in compat_fixture_payloads {
		bytes := p.bytes()
		assert object_name(bytes).hex() in loaded
		assert loaded[object_name(bytes).hex()] == bytes
	}
	assert loaded[object_name(fresh).hex()] == fresh

	// The migration is idempotent — a second write finds nothing to do.
	b2.put_object('cx-v017-second-wave'.bytes()) or {
		assert false, 'second put: ${err}'
		return
	}
	b2.flush_segment() or {
		assert false, 'second republish: ${err}'
		return
	}
	twice := os.read_bytes(fixture) or {
		assert false, 'read twice-written fixture: ${err}'
		return
	}
	assert twice == after, 'a second write moved the already-stamped pack'

	os.rmdir_all(dir) or {}
}

// ── pin (d): every OTHER code still fails closed ──────────────────────────

fn test_unimplemented_codes_still_fail_closed() {
	dir := compat_store_copy('cxstore_v015_badcode') or {
		assert false, 'stage fixture: ${err}'
		return
	}
	path := os.join_path(dir, compat_fixture_pack)
	// 0x13 = sha2-512: adjacent to sha2-256 in the multicodec registry, real,
	// and NOT implemented here. Accepting it would be reading a 64-byte digest
	// out of a 32-byte slot.
	for bad in [u16(0x0013), u16(0x001e), u16(0x0099)] {
		mut data := os.read_bytes(path) or {
			assert false, 'read: ${err}'
			return
		}
		data[header_size + 6] = u8(bad)
		data[header_size + 7] = u8(bad >> 8)
		os.write_file_array(path, data) or {
			assert false, 'rewrite: ${err}'
			return
		}
		if _ := open_pack(path) {
			assert false, 'open_pack accepted unimplemented multicodec 0x${bad:04x}'
		} else {
			assert err.msg().contains('unsupported hash multicodec'), 'wrong error for 0x${bad:04x}: ${err.msg()}'
		}
	}
	os.rmdir_all(dir) or {}
}
