#!/usr/bin/env bash
# consolidate_tests.sh — the #700 test-binary consolidation DRIVER
# (owner ruling 1a, 2026-08-09; generator requirements recorded on #700).
#
# The heavy lifting (parse / merge / dedupe / refusals) lives in CX:
# scripts/consolidate_tests.cx (dog-food). This wrapper owns the
# orchestration and the INDEPENDENT equivalence gate:
#
#   gen <area>     generate the umbrella OUTSIDE the input directory
#                  (scratch), re-verify the test-fn count with grep
#                  (independent of the generator's own claim), and
#                  prove idempotency (second run byte-identical).
#   apply <area>   gen + move the umbrella into the lane directory +
#                  compile-and-run it green + `git rm` the originals.
#                  The caller reviews and commits — ONE COMMIT PER AREA.
#   verify <area>  the gen-time checks only (no move, no git).
#   absorb <area>  fold NEW inputs into an umbrella that ALREADY exists:
#                  the roster is the live umbrella (its generated header
#                  block stripped so it is not nested inside the new one)
#                  plus the manifest's PENDING rows. Same equivalence +
#                  idempotency + compile-green gates as `apply`; on
#                  success the absorbed rows are `git rm`'d and rewritten
#                  in the manifest as `#absorbed <path>`, so the manifest
#                  stays the full provenance record and a re-run cannot
#                  double-absorb. `apply` still refuses to overwrite a
#                  live umbrella — that guard is what makes `absorb` an
#                  explicit, separate act.
#
# Manifests: scripts/consolidation/<area>.files — explicit, committed,
# one input path per line (# comments allowed). Exclusions (serial-retry
# rosters, #737 name-excluded, env-gated files) are simply never listed.
# `#absorbed <path>` rows are history: the file is gone, the umbrella
# carries it.
#
# Every check failure is a hard exit; nothing is deleted before the
# umbrella has compiled and run green in place.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CX_BIN="${CX_BIN:-$ROOT/vcx/target/cx}"
V_FLAGS=(-cc cc -gc e -d cx_db_sqlite -d cx_db_redis -usecache)

usage() { echo "usage: $0 {gen|verify|apply|absorb} <area>   (manifest: scripts/consolidation/<area>.files)"; exit 2; }

[ $# -eq 2 ] || usage
mode="$1"; area="$2"
case "$mode" in gen|verify|apply|absorb) : ;; *) usage ;; esac
manifest="scripts/consolidation/${area}.files"
[ -f "$manifest" ] || { echo "consolidate_tests: no manifest $manifest"; exit 2; }

# input roster (blank + # lines ignored). macOS bash 3.2: no mapfile.
pending=()
while IFS= read -r line; do
  pending+=("$line")
done < <(grep -vE '^[[:space:]]*(#|$)' "$manifest")
for f in "${pending[@]}"; do
  [ -f "$f" ] || { echo "consolidate_tests: manifest names missing file: $f"; exit 2; }
done

# every input must share one directory — the umbrella's home
[ "${#pending[@]}" -ge 1 ] || { echo "consolidate_tests: area '$area' has no pending inputs — nothing to merge"; exit 2; }
lane_dir="$(dirname "${pending[0]}")"
for f in "${pending[@]}"; do
  [ "$(dirname "$f")" = "$lane_dir" ] || { echo "consolidate_tests: inputs span directories ($lane_dir vs $(dirname "$f")) — one area, one lane dir"; exit 2; }
done

umbrella="${lane_dir}/${area}_umbrella_test.v"

# ── roster: absorb prepends the live umbrella, the other modes do not ──
if [ "$mode" = absorb ]; then
  [ -f "$umbrella" ] || { echo "consolidate_tests: absorb needs an existing $umbrella (use 'apply' to create one)"; exit 2; }
  # Strip the umbrella's own GENERATED header block in place, so it is not
  # nested inside the new one. In place (not a scratch copy) on purpose:
  # the generator stamps each section with its input PATH, and a mktemp
  # path would break the idempotency gate. Restored by `git checkout` on
  # any failure below.
  if head -1 "$umbrella" | grep -q -- '_umbrella_test\.v -- GENERATED by'; then
    awk 'NR==1{s=1} s==1 && /^\/\//{next} s==1 && /^[[:space:]]*$/{s=0;next} {print}' \
      "$umbrella" > "${umbrella}.hdrstrip"
    mv "${umbrella}.hdrstrip" "$umbrella"
    umbrella_touched=1
  fi
  inputs=("$umbrella" "${pending[@]}")
else
  [ "${#pending[@]}" -ge 2 ] || { echo "consolidate_tests: area '$area' has <2 inputs — nothing to merge"; exit 2; }
  inputs=("${pending[@]}")
fi
scratch="$(mktemp -d "${TMPDIR:-/tmp}/consolidate_${area}.XXXXXX")"
trap 'rm -rf "$scratch"' EXIT
out1="$scratch/${area}_umbrella_test.v"
out2="$scratch/${area}_umbrella_2_test.v"

# The generator is fed the RESOLVED roster (absorb prepends the umbrella
# and drops the `#absorbed` history rows), while MANIFEST_LABEL keeps the
# header pointing at the committed manifest — a scratch path in the
# header would break the idempotency gate.
roster="$scratch/roster.files"
printf '%s\n' "${inputs[@]}" > "$roster"

run_gen() { # $1 = out path
  MANIFEST="$roster" MANIFEST_LABEL="$manifest" OUT="$1" AREA="$area" \
    "$CX_BIN" --allow-read --allow-write --allow-env scripts/consolidate_tests.cx
}

# On any failure after the umbrella has been written: `apply` created it,
# so remove it; `absorb` REPLACED a committed file (and stripped its
# header before the run), so restore the committed bytes. Never leave a
# half-absorbed umbrella behind.
restore_umbrella() {
  [ "${umbrella_touched:-0}" = 1 ] || return 0
  if [ "$mode" = absorb ]; then
    git checkout -- "$umbrella"
  else
    rm -f "$umbrella"
  fi
}

echo "── consolidate[$area]: generate (${#inputs[@]} inputs → $out1)"
run_gen "$out1"

# ── independent equivalence gate ──────────────────────────────────────
tfns_in=$(cat "${inputs[@]}" | grep -c '^fn test_' || true)
tfns_out=$(grep -c '^fn test_' "$out1" || true)
if [ "$tfns_in" -ne "$tfns_out" ]; then
  echo "consolidate_tests: EQUIVALENCE FAIL — test fns in=$tfns_in out=$tfns_out"
  restore_umbrella
  exit 1
fi
echo "── consolidate[$area]: test-fn equivalence OK ($tfns_in == $tfns_out; grep, independent of the generator)"

run_gen "$out2" >/dev/null
if ! cmp -s "$out1" "$out2"; then
  echo "consolidate_tests: IDEMPOTENCY FAIL — two runs differ"
  restore_umbrella
  exit 1
fi
echo "── consolidate[$area]: idempotent (second run byte-identical)"

case "$mode" in
  gen|verify)
    echo "── consolidate[$area]: $mode complete (no move; umbrella at $out1)"
    exit 0 ;;
  apply|absorb) : ;;
esac

# ── apply/absorb: move in, prove green, then remove the originals ─────
if [ "$mode" = apply ]; then
  [ -e "$umbrella" ] && { echo "consolidate_tests: $umbrella already exists — regenerating over a live umbrella needs its originals; use 'absorb'"; exit 2; }
fi
cp "$out1" "$umbrella"
umbrella_touched=1
echo "── consolidate[$area]: umbrella in place ($umbrella); compile+run"
log="vcx/target/consolidate_${area}.log"
if ! v "${V_FLAGS[@]}" test "$umbrella" >"$log" 2>&1; then
  # #572 classified retry: a stale -usecache layer can inject a duplicate
  # or missing C symbol; a C compile/link failure gets ONE cache-free
  # retry (cache-free green proves the artifact). Anything else is real.
  if grep -aqE 'C compilation error|linker command failed|symbol\(s\) not found|duplicate symbol' "$log"; then
    echo "── consolidate[$area]: C compile/link failure — cache-free retry (#572 class)"
    nocache_flags=()
    for fl in "${V_FLAGS[@]}"; do [ "$fl" = "-usecache" ] || nocache_flags+=("$fl"); done
    if ! v "${nocache_flags[@]}" test "$umbrella" >"$log" 2>&1; then
      echo "consolidate_tests: umbrella RED (also cache-free) — originals untouched; log: $log"
      tail -20 "$log"
      restore_umbrella
      exit 1
    fi
  else
    echo "consolidate_tests: umbrella RED — originals untouched; log: $log"
    tail -20 "$log"
    restore_umbrella
    exit 1
  fi
fi
echo "── consolidate[$area]: umbrella GREEN ($(grep -c '^fn test_' "$umbrella") test fns); removing ${#pending[@]} absorbed original(s)"
git rm -q -- "${pending[@]}"
if [ "$mode" = absorb ]; then
  # The absorbed rows become history in the manifest: the file is gone,
  # the umbrella carries it. A second `absorb` then finds no pending row
  # and refuses instead of double-absorbing.
  absorbed_list=$(printf '%s\n' "${pending[@]}")
  awk -v list="$absorbed_list" '
    BEGIN { n = split(list, a, "\n"); for (i = 1; i <= n; i++) m[a[i]] = 1 }
    { if ($0 in m) print "#absorbed " $0; else print }' \
    "$manifest" > "${manifest}.new"
  mv "${manifest}.new" "$manifest"
  echo "── consolidate[$area]: ${#pending[@]} manifest row(s) marked #absorbed"
fi
echo "── consolidate[$area]: done — review + commit (one commit per area). Log: $log"
