#!/usr/bin/env bash
# consolidate_tests_selftest — proves the #700 driver's absorb restore on a
# SYNTHETIC repo (mktemp; never the tracked tree — the same rule the
# spec-freeze-gate self-test follows). `absorb` strips the COMMITTED
# umbrella's generated header IN PLACE before it generates; the driver's own
# sentence is "Never leave a half-absorbed umbrella behind", and these cases
# are that sentence, executable. Four scenarios, every one against a copy of
# the live scripts/consolidate_tests.sh:
#   A  CX_BIN names a path that does not exist   → MUST exit non-zero AND
#      leave the committed umbrella byte-identical   (#1392, the measured
#      defect: `absorb` before vcx/target/cx was built left the committed
#      umbrella header-stripped, because `set -e` exits past the two explicit
#      restore calls and the EXIT trap only removed the scratch dir)
#   B  CX_BIN exists but the generator FAILS      → same two assertions (the
#      class A's cheap pre-flight cannot see; only the EXIT trap closes it)
#   C  the generator breaks the test-fn equivalence gate → same two assertions
#      (the explicit-failure path that always restored; the regression guard
#      on folding those calls into the trap)
#   D  a generator and a compiler that both succeed → absorb COMPLETES: the
#      umbrella is the newly generated one, the absorbed row is rewritten
#      `#absorbed`, the original is gone. The guard that the restore-on-exit
#      never runs on the success path.
set -euo pipefail

DRIVER="$(cd "$(dirname "$0")" && pwd)/consolidate_tests.sh"
T=$(mktemp -d "${TMPDIR:-/tmp}/consolidate_selftest.XXXXXX")
trap 'rm -rf "$T"' EXIT
# The fake generators and compiler live OUTSIDE the repo: every scenario
# asserts a CLEAN `git status`, so nothing that is not part of the fixture
# may sit inside the worktree.
mkdir -p "$T/bin" "$T/repo"

UMBRELLA=vcx/tests/demo_umbrella_test.v
MANIFEST=scripts/consolidation/demo.files
PENDING=vcx/tests/demo_b_test.v

(
  cd "$T/repo"
  git init -q .
  git config user.email t@t && git config user.name t
  mkdir -p scripts/consolidation vcx/tests vcx/target

  cp "$DRIVER" scripts/consolidate_tests.sh

  # The manifest: one history row (its original is gone, as #1012 requires)
  # and one pending row — the shape `absorb` is for.
  cat > "$MANIFEST" <<'EOF'
# demo area for the self-test
#absorbed vcx/tests/demo_a_test.v
vcx/tests/demo_b_test.v
EOF

  # The committed umbrella: a generated header block (first seven lines here,
  # as in the tree) over one absorbed section.
  cat > "$UMBRELLA" <<'EOF'
// demo_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):
// the per-area test-binary umbrella. 1 source file merged verbatim.
// Regenerate: scripts/consolidate_tests.sh gen demo
// Manifest:   scripts/consolidation/demo.files

// ── source: vcx/tests/demo_a_test.v ──
module main

fn test_a() {
	assert true
}
EOF

  cat > "$PENDING" <<'EOF'
module main

fn test_b() {
	assert true
}
EOF

  git add -A && git commit -qm "seed the demo area"
  committed_umbrella="$(git rev-parse HEAD:"$UMBRELLA")"

  # A generator that behaves like scripts/consolidate_tests.cx does for the
  # gates this driver runs: the roster in, one file out, the umbrella's own
  # body carried through, a `// ── source:` stamp on every new input, every
  # `fn test_` preserved, and byte-identical across runs.
  cat > "$T/bin/cx-ok" <<'EOF'
#!/bin/sh
{
  echo "// ${AREA}_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):"
  echo "// Manifest:   ${MANIFEST_LABEL}"
  echo ""
  while IFS= read -r f; do
    case "$f" in
      *_umbrella_test.v) cat "$f" ;;
      *) echo "// ── source: $f ──"; cat "$f" ;;
    esac
  done < "$MANIFEST"
} > "$OUT"
EOF
  # the same generator, dropping the new input's test fn — the equivalence
  # gate's in != out.
  cat > "$T/bin/cx-eqfail" <<'EOF'
#!/bin/sh
{
  echo "// ${AREA}_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):"
  echo "// Manifest:   ${MANIFEST_LABEL}"
  echo ""
  while IFS= read -r f; do
    case "$f" in
      *_umbrella_test.v) cat "$f" ;;
      *) echo "// ── source: $f ──"; sed '/^fn test_/d' "$f" ;;
    esac
  done < "$MANIFEST"
} > "$OUT"
EOF
  printf '#!/bin/sh\nexit 3\n' > "$T/bin/cx-err"
  # `v` is invoked bare, off PATH: a compiler that says green, so case D can
  # reach the end of the driver without a real build.
  printf '#!/bin/sh\nexit 0\n' > "$T/bin/v"
  chmod +x "$T/bin/cx-ok" "$T/bin/cx-eqfail" "$T/bin/cx-err" "$T/bin/v"
  PATH="$T/bin:$PATH"; export PATH

  assert_untouched() { # $1 = scenario letter, $2 = the exit the driver gave
    local case="$1" rc="$2"
    if [ "$rc" -eq 0 ]; then
      echo "SELFTEST FAILED: scenario $case — absorb exited 0 with a generator that could not have produced an umbrella" >&2
      exit 1
    fi
    if [ "$(git rev-parse HEAD:"$UMBRELLA")" != "$committed_umbrella" ]; then
      echo "SELFTEST FAILED: scenario $case — the self-test's own committed umbrella moved" >&2
      exit 1
    fi
    if ! git diff --quiet -- "$UMBRELLA"; then
      echo "SELFTEST FAILED (#1392): scenario $case — absorb exited $rc and left the COMMITTED $UMBRELLA modified:" >&2
      git --no-pager diff --stat -- "$UMBRELLA" >&2
      git --no-pager diff -- "$UMBRELLA" | head -20 >&2
      exit 1
    fi
    if [ -n "$(git status --porcelain)" ]; then
      echo "SELFTEST FAILED: scenario $case — absorb exited $rc and left the tree dirty:" >&2
      git status --porcelain >&2
      exit 1
    fi
  }

  # A — CX_BIN that does not exist (the measured #1392 path: absorb run
  # before vcx/target/cx was built; the generator exits 127).
  rc=0
  CX_BIN="$T/bin/does-not-exist-cx" bash scripts/consolidate_tests.sh absorb demo >/dev/null 2>&1 || rc=$?
  assert_untouched A "$rc"

  # B — CX_BIN exists and is executable, but the generator fails. The cheap
  # pre-flight cannot see this one; the EXIT trap is what restores.
  rc=0
  CX_BIN="$T/bin/cx-err" bash scripts/consolidate_tests.sh absorb demo >/dev/null 2>&1 || rc=$?
  assert_untouched B "$rc"

  # C — the generator loses a test fn: the equivalence gate refuses.
  rc=0
  CX_BIN="$T/bin/cx-eqfail" bash scripts/consolidate_tests.sh absorb demo >/dev/null 2>&1 || rc=$?
  assert_untouched C "$rc"

  # D — the success path: absorb must COMPLETE, and the restore must not run.
  rc=0
  CX_BIN="$T/bin/cx-ok" bash scripts/consolidate_tests.sh absorb demo > "$T/absorb.log" 2>&1 || rc=$?
  if [ "$rc" -ne 0 ]; then
    echo "SELFTEST FAILED: scenario D — a working absorb exited $rc:" >&2
    cat "$T/absorb.log" >&2
    exit 1
  fi
  if git diff --quiet -- "$UMBRELLA"; then
    echo "SELFTEST FAILED: scenario D — a successful absorb left $UMBRELLA at its committed bytes (the restore ran on the success path)" >&2
    exit 1
  fi
  grep -q '^fn test_a' "$UMBRELLA" && grep -q '^fn test_b' "$UMBRELLA" || {
    echo "SELFTEST FAILED: scenario D — the absorbed umbrella does not carry both sections" >&2; exit 1; }
  grep -q "^#absorbed $PENDING\$" "$MANIFEST" || {
    echo "SELFTEST FAILED: scenario D — the manifest row was not rewritten as history" >&2; exit 1; }
  [ ! -e "$PENDING" ] || {
    echo "SELFTEST FAILED: scenario D — the absorbed original is still in the tree" >&2; exit 1; }
)

echo "consolidate-tests selftest: 4/4 (missing CX_BIN, generator failure, equivalence failure — each non-zero with the committed umbrella intact; a working absorb completes)"
