module main

import os

// gen_nfc_tables — generates vcx/cx/nfc_tables.v from the pinned Unicode
// Character Database (I1 identity epoch, stream 12 L22/L23; owner ruling
// (a): CX-owned generated tables, generator committed).
//
// Inputs (committed at tools/ucd/<version>/, downloaded 2026-08-05):
//   UnicodeData.txt               sha256 ff58e5823bd095166564a006e47d1111…
//   CompositionExclusions.txt     sha256 89e83cf9cc8bef6c1f8bf77e42cf6f03…
//   DerivedNormalizationProps.txt (retained for audit; the exclusion set
//                                  is derived below per UAX #15 §5)
//
// Run from the repo root:
//   third_party/v/v run tools/gen_nfc_tables.v
//
// The output tables are FROZEN identity inputs: canonical name bytes ride
// them. Regenerating against a NEWER UCD version is an identity migration
// and needs an owner ruling, exactly like re-syncing the vendored Ryū.

const ucd_version = '16.0.0'
const ucd_dir = 'tools/ucd/${ucd_version}'
const out_path = 'vcx/cx/nfc_tables.v'

struct Decomp {
mut:
	cps []u32
}

fn parse_cp(s string) u32 {
	return u32(s.trim_space().parse_uint(16, 32) or { 0 })
}

fn main() {
	ud := os.read_file('${ucd_dir}/UnicodeData.txt') or {
		panic('missing ${ucd_dir}/UnicodeData.txt — download the pinned UCD first')
	}
	excl_txt := os.read_file('${ucd_dir}/CompositionExclusions.txt') or {
		panic('missing CompositionExclusions.txt')
	}

	mut ccc := map[u32]int{}
	mut decomp := map[u32]Decomp{}

	for line in ud.split_into_lines() {
		if line.len == 0 {
			continue
		}
		f := line.split(';')
		if f.len < 6 {
			continue
		}
		cp := parse_cp(f[0])
		c := f[3].int()
		if c != 0 {
			ccc[cp] = c
		}
		d := f[5].trim_space()
		if d.len > 0 && !d.starts_with('<') {
			// canonical decomposition only (compat mappings carry a <tag>)
			mut cps := []u32{}
			for part in d.split(' ') {
				if part.len > 0 {
					cps << parse_cp(part)
				}
			}
			if cps.len > 0 {
				decomp[cp] = Decomp{ cps: cps }
			}
		}
	}

	// Fully expand decompositions (canonical closure).
	mut full := map[u32][]u32{}
	for cp, _ in decomp {
		full[cp] = expand(cp, decomp)
	}

	// Composition exclusions: the listed set + derived (singletons and
	// non-starter decompositions), per UAX #15 §5.
	mut excluded := map[u32]bool{}
	for line in excl_txt.split_into_lines() {
		l := line.all_before('#').trim_space()
		if l.len == 0 {
			continue
		}
		excluded[parse_cp(l)] = true
	}
	mut pairs := map[u64]u32{}
	for cp, d in decomp {
		if d.cps.len != 2 {
			continue // singleton decompositions never recompose
		}
		if excluded[cp] {
			continue
		}
		first_ccc := ccc[d.cps[0]] or { 0 }
		self_ccc := ccc[cp] or { 0 }
		if first_ccc != 0 || self_ccc != 0 {
			continue // non-starter decomposition
		}
		key := (u64(d.cps[0]) << 32) | u64(d.cps[1])
		pairs[key] = cp
	}

	// ── Emit ──
	mut b := []string{}
	b << 'module cx'
	b << ''
	b << '// nfc_tables.v — GENERATED by tools/gen_nfc_tables.v from UCD ${ucd_version}'
	b << '// (pinned sources at tools/ucd/${ucd_version}/). DO NOT EDIT BY HAND and do'
	b << '// not regenerate against a newer UCD without an owner-ruled identity'
	b << '// migration: canonical NAME bytes ride these tables (I1 L22/L23).'
	b << ''

	// CCC: sorted flat (cp, ccc) pairs.
	mut ccc_keys := ccc.keys()
	ccc_keys.sort()
	b << 'const cx_nfc_ccc_flat = ['
	mut line := '\t'
	for i, cp in ccc_keys {
		line += 'u32(0x${cp:x}), ${ccc[cp]}, '
		if (i + 1) % 8 == 0 {
			b << line
			line = '\t'
		}
	}
	if line.trim_space().len > 0 {
		b << line
	}
	b << ']!'
	b << ''

	// Decompositions: sorted keys; spans (offset<<8 | len) into a flat pool.
	mut dk := full.keys()
	dk.sort()
	mut pool := []u32{}
	mut spans := []string{}
	mut keys_out := []string{}
	for cp in dk {
		cps := full[cp]
		off := pool.len
		for c in cps {
			pool << c
		}
		keys_out << '0x${cp:x}'
		spans << '${off * 256 + cps.len}'
	}
	b << 'const cx_nfc_decomp_keys = ['
	line = '\t'
	for i, k in keys_out {
		line += 'u32(${k}), '
		if (i + 1) % 10 == 0 {
			b << line
			line = '\t'
		}
	}
	if line.trim_space().len > 0 {
		b << line
	}
	b << ']!'
	b << ''
	b << 'const cx_nfc_decomp_spans = ['
	line = '\t'
	for i, s in spans {
		line += 'u32(${s}), '
		if (i + 1) % 10 == 0 {
			b << line
			line = '\t'
		}
	}
	if line.trim_space().len > 0 {
		b << line
	}
	b << ']!'
	b << ''
	b << 'const cx_nfc_decomp_pool = ['
	line = '\t'
	for i, c in pool {
		line += 'u32(0x${c:x}), '
		if (i + 1) % 10 == 0 {
			b << line
			line = '\t'
		}
	}
	if line.trim_space().len > 0 {
		b << line
	}
	b << ']!'
	b << ''

	// Composition pairs: sorted by packed (first<<32|second) key.
	mut pk := pairs.keys()
	pk.sort()
	b << 'const cx_nfc_comp_keys = ['
	line = '\t'
	for i, k in pk {
		line += 'u64(0x${k:x}), '
		if (i + 1) % 6 == 0 {
			b << line
			line = '\t'
		}
	}
	if line.trim_space().len > 0 {
		b << line
	}
	b << ']!'
	b << ''
	b << 'const cx_nfc_comp_vals = ['
	line = '\t'
	for i, k in pk {
		line += 'u32(0x${pairs[k]:x}), '
		if (i + 1) % 10 == 0 {
			b << line
			line = '\t'
		}
	}
	if line.trim_space().len > 0 {
		b << line
	}
	b << ']!'

	os.write_file(out_path, b.join('\n') + '\n') or { panic(err) }
	println('wrote ${out_path}: ccc=${ccc_keys.len} decomp=${dk.len} pool=${pool.len} comp=${pk.len}')
}

fn expand(cp u32, decomp map[u32]Decomp) []u32 {
	d := decomp[cp] or { return [cp] }
	mut out := []u32{}
	for c in d.cps {
		out << expand(c, decomp)
	}
	return out
}
